import streamlit as st
st.set_page_config(page_title='My Favourite')
st.markdown("<h3 style='color:black;font-size:36px'>Dreaming...</h3>",unsafe_allow_html=True)
st.markdown("<h3 style='color: blue;'>Cars</h3>",unsafe_allow_html=True)

st.header("Cool.........")
st.subheader("Car1")
st.image("./car1.jpg",width=500,use_column_width=True)
st.subheader("Car2")
st.image("./car2.jpg",width=500,use_column_width=True)
st.subheader("Car3")
st.image("./car3.jpg",width=500,use_column_width=True)
st.subheader("Car4")
st.image("./car4.jpg",width=500,use_column_width=True)
st.subheader("Car5")
st.image("./car5.jpg",width=500,use_column_width=True)
st.subheader("Car6")
st.image("./car6.jpg",width=500,use_column_width=True)
st.subheader("Bike1")
st.image("./bike1.jpg",width=500,use_column_width=True)
st.subheader("Bike2")
st.image("./bike2.jpg",width=500,use_column_width=True)
st.subheader("Bike3")
st.image("./bike3.jpg",width=500,use_column_width=True)
st.subheader("Bike4")
st.image("./bike4.jpg",width=500,use_column_width=True)
st.subheader("Bike5")
st.image("./bike5.jpg",width=500,use_column_width=True)
st.subheader("Bike6")
st.image("./bike6.jpg",width=500,use_column_width=True)
st.subheader("Jeep1")
st.image("./jeep1.jpg",width=500,use_column_width=True)
st.subheader("Jeep2")
st.image("./jeep2.jpg",width=500,use_column_width=True)
st.subheader("Jeep3")
st.image("./jeep3.jpg",width=500,use_column_width=True)
st.subheader("Jeep4")
st.image("./jeep4.jpg",width=500,use_column_width=True)
st.subheader("Jeep5")
st.image("./jeep5.jpg",width=500,use_column_width=True)
st.subheader("Jeep6")
st.image("./jeep6.jpg",width=500,use_column_width=True)
  
  
  
  
  
